export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const PROJECTS_LIST = 'PROJECTS_LIST';

export const DELETE_TASK = 'DELETE_TASK';
export const ADD_TASK_BY_DAYS = 'ADD_TASK_BY_DAYS';
export const ADD_TASK_BY_PROJECT = 'ADD_TASK_BY_PROJECT';
export const TASK_LIST = 'TASK_LIST';
export const TASKS_FOR_TODAY = 'TASKS_FOR_TODAY';
export const TASKS_BY_PROJECT = 'TASKS_FOR_TODAY';

